image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview

tasks:
  - name: Start GUI + Run JavaFX App
    command: |
      # Start VNC server
      vncserver :1 -geometry 1280x800 -localhost no

      # Bridge VNC → noVNC
      websockify --web /usr/share/novnc/ 6080 localhost:5901 &

      # Give VNC a moment to start
      sleep 3

      # Export display so JavaFX can open a window
      export DISPLAY=:1

      # Compile and run your program
      javac --module-path /usr/share/openjfx/lib --add-modules javafx.controls,javafx.fxml ElasticBandImplement.java
      java --module-path /usr/share/openjfx/lib --add-modules javafx.controls,javafx.fxml ElasticBandImplement
