image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview

tasks:
  - name: Start JavaFX App
    init: |
      sudo apt-get update
      sudo apt-get install -y openjfx tigervnc-standalone-server novnc websockify
      javac --module-path /usr/share/openjfx/lib --add-modules javafx.controls,javafx.fxml ElasticBandImplement.java
    command: |
      vncserver :1 -geometry 1024x768 -localhost no
      websockify --web /usr/share/novnc/ 6080 localhost:5901 &

      echo "⏳ Waiting for VNC server to be ready..."
      for i in {1..15}; do
        if [ -e /tmp/.X11-unix/X1 ]; then
          echo "✅ VNC server is ready."
          break
        fi
        sleep 1
      done

      export DISPLAY=:1
      java --module-path /usr/share/openjfx/lib --add-modules javafx.controls,javafx.fxml ElasticBandImplement
